# Generated by Django 4.2 on 2023-04-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
    ]
